### ISSUE TITLE
ReadPBMessageMonad assertion failure on large reads

### ISSUE THREAD

**Issue by jamesclampffer** [haohui/libhdfspp#29]
When reading a 1GB file locally the assertion on line 96 of lib/common/protobuf_util.h fails at or slightly after byte 134086656.

Error printed to console:
src/main/native/lib/common/protobuf_util.h:96: size_t hdfs::ReadPBMessageMonad<Stream, Message, MaxMessageSize>::CompletionHandler(const error_code&, size_t) [with Stream = asio::basic_stream_socketasio::ip::tcp; Message = hadoop::hdfs::BlockOpResponseProto; long unsigned int MaxMessageSize = 512ul; size_t = long unsigned int; asio::error_code = std::error_code]: Assertion `offset + len < buf_.size()' failed.

Reproducer code using my "c_read_api" branch to provide compatibility with libhdfs(3):
# include "libhdfs++/chdfs.h"
# include <cstdint>
# include <cstring>
# include <iostream>
# include <string>
# include <vector>

int main(int argc, char **argv) {
  if(argc != 4) {
    std::cout << "usage: ./perf_tests <host> <port> <file> [...]" << std::endl;
    return 1;
  }

  hdfsFS fs = hdfsConnect(argv[1], std::atoi(argv[2]));
  hdfsFile file = hdfsOpenFile(fs, argv[3], 0, 0, 0, 0);
  std::vector<char> buffer;
  buffer.reserve(MB);

  long total = 0;
  while(1) {
    long count = hdfsPread(fs, file, total, &buffer[0], 50000);
    std::cout << "read " << total << std::endl;
    total += count;
    if(count <= 0)
      break;
  }
  return 0;
}

Changing the request size from 50000 to other numbers results in failures at slightly different byte offsets, but usually ~130MB into the file.

**Comment by jamesclampffer** [comment]
Realized this is right at the block boundary for the file (128MB blocks).  This may not actually be an error; need to check if hdfs::InputStream is supports files that span multiple blocks.

**Comment by haohui** [comment]
You might be hitting a kernel bug:

http://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/

**Comment by jamesclampffer** [comment]
I'll look into that as well as give this a shot on some different hardware with a different kernel; I need to do that for perf tests anyway.  So the hdfs::InputStream should be able to read across block boundaries?

**Comment by haohui** [comment]
InputStream should work across the block boundaries.

https://github.com/haohui/libhdfspp/commit/c019cd1cf897f5d02d20dee54670549f29e473d6 should fix it.

**Comment by jamesclampffer** [comment]
Thanks for the patch!  Reads will still report -1 on block boundaries but they don't throw anymore.
