### ISSUE TITLE
Remote block reader sends wrong kDataTransferVersion

### ISSUE THREAD

**Issue by jamesclampffer** [haohui/libhdfspp#32]
On some read requests InputStreamImpl::PositionRead will read 0 bytes and the DN log shows this message: 

java.io.IOException: Version Mismatch (Expected: 28, Received: 520 )
        at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.readOp(Receiver.java:57)
        at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:206)
        at java.lang.Thread.run(Thread.java:619)

I've only seen this happen when attempting to read exactly 2MB.  Smaller reads seem to work; including reads that span multiple packets.

State->request in RemoteBlockReader<>::async_connect is always "\000\034Q", I suspect that there is an issue when this and the hdfs::OpReadBlockProto are serialized in AppendToDelimitedString but I haven't found anything that looks strange yet.

**Comment by jamesclampffer** [comment]
Reads of 2MB-1 fail in the same way, but 2MB+1 work correctly.

**Comment by haohui** [comment]
It's working fine for me.

```
$./inputstream_test 127.0.0.1 19000 /4m
Read bytes:2097152
```

Can you describe how you reproduce the issue?

**Comment by jamesclampffer** [comment]
I'll have to work on getting a standalone reproducer set up, right now this is part of a larger integration test.

**Comment by jamesclampffer** [comment]
It looks like this was a side effect of the bug that leaked block_readers due to shared_ptrs that Haohui fixed a while back.  Thousands of sockets were in CLOSE_WAIT state and reads were giving odd results.  Something to look for if this error message shows up in the hdfs datanode logs again.
