### ISSUE TITLE
InputStream never calls RemoteBlockReader destructor

### ISSUE THREAD

**Issue by jamesclampffer** [haohui/libhdfspp#33]
RemoteBlockReader's destructor never gets called so none of the resources it holds are never freed.  The easy way of testing is to add a destructor to RemoteBlockReader:
~RemoteBlockReader() {std::cerr << "~RemoteBlockReader" << std::endl;};
and then run  inputstream_test.  No "~RemoteBlockReader" message will show up.

For more details I used valgrind's dynamic heap analysis tool (DHAT).  This shows that a lot of the resources the RemoteBlockReader holds on to don't get freed because they rely on RAII.  The biggest leaks are checksum_ and what looks like header_.  These leaks start getting very large when running perf_tests in my performance testing branch.

**Comment by jamesclampffer** [comment]
It looks like this is due to the destructor for InputStreamImpl::AsyncPreadSome::State never being called, and that holds the RemoteBlockReader (also leaking the socket).  

I'm guessing there is a cycle of shared_ptr<State> in the monad chain at the bottom of AsyncPreadSome but I haven't been able to find it yet.

**Comment by haohui** [comment]
It might due to the unclear life cycles in the monad. What I ended up is to move away from the monad to continuation, and to clarify the contracts on managing the life cycles of objects.

I got a clean valgrind run on the latest tip (d173d0):

```
valgrind --leak-check=full lib/fs/inputstream_test 127.0.0.1 19000 /4m 
...
==86373== HEAP SUMMARY:
==86373==     in use at exit: 86,056 bytes in 1,365 blocks
==86373==   total heap usage: 6,744 allocs, 5,379 frees, 383,039 bytes allocated
==86373== 
==86373== LEAK SUMMARY:
==86373==    definitely lost: 0 bytes in 0 blocks
==86373==    indirectly lost: 0 bytes in 0 blocks
==86373==      possibly lost: 0 bytes in 0 blocks
...
```

Please see whether it fixes the issue.

**Comment by jamesclampffer** [comment]
Great, I'll try to get this running today.

**Comment by jamesclampffer** [comment]
Valgrind memcheck and DHAT produce good results on large data sets.
