### ISSUE TITLE
Default to reading local replica if one exists

### ISSUE THREAD

**Issue by jamesclampffer** [haohui/libhdfspp#45]
Right now AsyncPreadSome chooses a replica to read from based on the order that replicas are placed in the RPC response by the namenode.  It places them in the endpoints list using a loop:

for (auto &loc : it->locs()) {
      auto datanode = loc.id();
      s.endpoints.push_back(tcp::endpoint(ip::address::from_string(datanode.ipaddr()), datanode.xferport()));
}

Add check in this block of code to make sure that a local replica is always the first endpoint tried by the asio::tcp_resolver.  This will ease network congestion and will also provide a logical place to hook in the local_block_reader.

**Comment by haohui** [comment]
The list of DNs is always sorted based on the locality of the block, which means that the local DN is guaranteed to appear at the very beginning of the list.

**Comment by jamesclampffer** [comment]
Oh that's handy, thanks for the info.  I'll close this then.
