### ISSUE TITLE
GCC 4.7.2 internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by Mrknowledge** [haohui/libhdfspp#48]
I've got errors while make libhdfspp source code :
[root@Sla3 build]# make
[  2%] Running C++ protocol buffer compiler on ClientNamenodeProtocol.proto
[  4%] Running C++ protocol buffer compiler on datatransfer.proto
[  6%] Running C++ protocol buffer compiler on hdfs.proto
[  9%] Running C++ protocol buffer compiler on Security.proto
[ 11%] Running C++ protocol buffer compiler on IpcConnectionContext.proto
[ 13%] Running C++ protocol buffer compiler on ProtobufRpcEngine.proto
[ 16%] Running C++ protocol buffer compiler on RpcHeader.proto
[ 18%] Running C++ protocol buffer compiler on acl.proto
[ 20%] Running C++ protocol buffer compiler on xattr.proto
[ 23%] Running C++ protocol buffer compiler on encryption.proto
[ 25%] Running C++ protocol buffer compiler on inotify.proto
Scanning dependencies of target proto
[ 27%] Building CXX object lib/proto/CMakeFiles/proto.dir/datatransfer.pb.cc.o
[ 30%] Building CXX object lib/proto/CMakeFiles/proto.dir/hdfs.pb.cc.o
[ 32%] Building CXX object lib/proto/CMakeFiles/proto.dir/Security.pb.cc.o
[ 34%] Building CXX object lib/proto/CMakeFiles/proto.dir/IpcConnectionContext.pb.cc.o
[ 37%] Building CXX object lib/proto/CMakeFiles/proto.dir/ProtobufRpcEngine.pb.cc.o
[ 39%] Building CXX object lib/proto/CMakeFiles/proto.dir/RpcHeader.pb.cc.o
[ 41%] Building CXX object lib/proto/CMakeFiles/proto.dir/acl.pb.cc.o
[ 44%] Building CXX object lib/proto/CMakeFiles/proto.dir/xattr.pb.cc.o
[ 46%] Building CXX object lib/proto/CMakeFiles/proto.dir/encryption.pb.cc.o
[ 48%] Building CXX object lib/proto/CMakeFiles/proto.dir/inotify.pb.cc.o
[ 51%] Building CXX object lib/proto/CMakeFiles/proto.dir/ClientNamenodeProtocol.pb.cc.o
Linking CXX static library libproto.a
[ 51%] Built target proto
Scanning dependencies of target common
[ 53%] Building CXX object lib/common/CMakeFiles/common.dir/hdfs.cc.o
[ 55%] Building CXX object lib/common/CMakeFiles/common.dir/base64.cc.o
[ 58%] Building CXX object lib/common/CMakeFiles/common.dir/datatransfer_sasl.cc.o
In file included from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/common/datatransfer_sasl.cc:19:0:
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/common/datatransfer_sasl.h: In lambda function:
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/common/datatransfer_sasl.h:130:72: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See http://bugzilla.redhat.com/bugzilla for instructions.
Preprocessed source stored into /tmp/cc12J0uV.out file, please attach this to your bugreport.
make[2]: **\* [lib/common/CMakeFiles/common.dir/datatransfer_sasl.cc.o] Error 1
make[1]: **\* [lib/common/CMakeFiles/common.dir/all] Error 2
make: **\* [all] Error 2

**Comment by bobhansen** [comment]
GCC 4.7 isn't up to snuff to compile C++11 code.  We're testing on GCC 4.8 and above (and 4.8 has some issues that have bit us, especially in the std::regex code).

-Bob

On 02/18/2016 03:52 AM, Mrknowledge wrote:

I've got errors while make libhdfspp source code :
[root@Sla3 build]# make
[ 2%] Running C++ protocol buffer compiler on ClientNamenodeProtocol.proto
[ 4%] Running C++ protocol buffer compiler on datatransfer.proto
[ 6%] Running C++ protocol buffer compiler on hdfs.proto
[ 9%] Running C++ protocol buffer compiler on Security.proto
[ 11%] Running C++ protocol buffer compiler on IpcConnectionContext.proto
[ 13%] Running C++ protocol buffer compiler on ProtobufRpcEngine.proto
[ 16%] Running C++ protocol buffer compiler on RpcHeader.proto
[ 18%] Running C++ protocol buffer compiler on acl.proto
[ 20%] Running C++ protocol buffer compiler on xattr.proto
[ 23%] Running C++ protocol buffer compiler on encryption.proto
[ 25%] Running C++ protocol buffer compiler on inotify.proto
Scanning dependencies of target proto
[ 27%] Building CXX object lib/proto/CMakeFiles/proto.dir/datatransfer.pb.cc.o
[ 30%] Building CXX object lib/proto/CMakeFiles/proto.dir/hdfs.pb.cc.o
[ 32%] Building CXX object lib/proto/CMakeFiles/proto.dir/Security.pb.cc.o
[ 34%] Building CXX object lib/proto/CMakeFiles/proto.dir/IpcConnectionContext.pb.cc.o
[ 37%] Building CXX object lib/proto/CMakeFiles/proto.dir/ProtobufRpcEngine.pb.cc.o
[ 39%] Building CXX object lib/proto/CMakeFiles/proto.dir/RpcHeader.pb.cc.o
[ 41%] Building CXX object lib/proto/CMakeFiles/proto.dir/acl.pb.cc.o
[ 44%] Building CXX object lib/proto/CMakeFiles/proto.dir/xattr.pb.cc.o
[ 46%] Building CXX object lib/proto/CMakeFiles/proto.dir/encryption.pb.cc.o
[ 48%] Building CXX object lib/proto/CMakeFiles/proto.dir/inotify.pb.cc.o
[ 51%] Building CXX object lib/proto/CMakeFiles/proto.dir/ClientNamenodeProtocol.pb.cc.o
Linking CXX static library libproto.a
[ 51%] Built target proto
Scanning dependencies of target common
[ 53%] Building CXX object lib/common/CMakeFiles/common.dir/hdfs.cc.o
[ 55%] Building CXX object lib/common/CMakeFiles/common.dir/base64.cc.o
[ 58%] Building CXX object lib/common/CMakeFiles/common.dir/datatransfer_sasl.cc.o
In file included from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/common/datatransfer_sasl.cc:19:0:
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/common/datatransfer_sasl.h: In lambda function:
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/common/datatransfer_sasl.h:130:72: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See http://bugzilla.redhat.com/bugzilla for instructions.
Preprocessed source stored into /tmp/cc12J0uV.out file, please attach this to your bugreport.
make[2]: **\* [lib/common/CMakeFiles/common.dir/datatransfer_sasl.cc.o] Error 1
make[1]: **\* [lib/common/CMakeFiles/common.dir/all] Error 2
make: **\* [all] Error 2

�

**Comment by Mrknowledge** [comment]
OK. Thx.
