### ISSUE TITLE
fatal error: me_haohui_libhdfspp_NativeRemoteBlockReader.h: No such file or directory

### ISSUE THREAD

**Issue by Mrknowledge** [haohui/libhdfspp#49]
I've got errors while make libhdfspp source code :

[root@Sla3 build]# make
[  2%] Running C++ protocol buffer compiler on ClientNamenodeProtocol.proto
[  4%] Running C++ protocol buffer compiler on datatransfer.proto
[  6%] Running C++ protocol buffer compiler on hdfs.proto
[  9%] Running C++ protocol buffer compiler on Security.proto
[ 11%] Running C++ protocol buffer compiler on IpcConnectionContext.proto
[ 13%] Running C++ protocol buffer compiler on ProtobufRpcEngine.proto
[ 16%] Running C++ protocol buffer compiler on RpcHeader.proto
[ 18%] Running C++ protocol buffer compiler on acl.proto
[ 20%] Running C++ protocol buffer compiler on xattr.proto
[ 23%] Running C++ protocol buffer compiler on encryption.proto
[ 25%] Running C++ protocol buffer compiler on inotify.proto
Scanning dependencies of target proto
[ 27%] Building CXX object lib/proto/CMakeFiles/proto.dir/datatransfer.pb.cc.o
[ 30%] Building CXX object lib/proto/CMakeFiles/proto.dir/hdfs.pb.cc.o
[ 32%] Building CXX object lib/proto/CMakeFiles/proto.dir/Security.pb.cc.o
[ 34%] Building CXX object lib/proto/CMakeFiles/proto.dir/IpcConnectionContext.pb.cc.o
[ 37%] Building CXX object lib/proto/CMakeFiles/proto.dir/ProtobufRpcEngine.pb.cc.o
[ 39%] Building CXX object lib/proto/CMakeFiles/proto.dir/RpcHeader.pb.cc.o
[ 41%] Building CXX object lib/proto/CMakeFiles/proto.dir/acl.pb.cc.o
[ 44%] Building CXX object lib/proto/CMakeFiles/proto.dir/xattr.pb.cc.o
[ 46%] Building CXX object lib/proto/CMakeFiles/proto.dir/encryption.pb.cc.o
[ 48%] Building CXX object lib/proto/CMakeFiles/proto.dir/inotify.pb.cc.o
[ 51%] Building CXX object lib/proto/CMakeFiles/proto.dir/ClientNamenodeProtocol.pb.cc.o
Linking CXX static library libproto.a
[ 51%] Built target proto
Scanning dependencies of target common
[ 53%] Building CXX object lib/common/CMakeFiles/common.dir/hdfs.cc.o
[ 55%] Building CXX object lib/common/CMakeFiles/common.dir/base64.cc.o
[ 58%] Building CXX object lib/common/CMakeFiles/common.dir/datatransfer_sasl.cc.o
[ 60%] Building CXX object lib/common/CMakeFiles/common.dir/sasl_digest_md5.cc.o
[ 62%] Building CXX object lib/common/CMakeFiles/common.dir/status.cc.o
Linking CXX static library libcommon.a
[ 62%] Built target common
Scanning dependencies of target fs
[ 65%] Building CXX object lib/fs/CMakeFiles/fs.dir/filesystem.cc.o
In file included from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/filesystem.h:21:0,
                 from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/filesystem.cc:19:
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/namenode_protocol.h:40:2: warning: extra ‘;’ [-Wpedantic]
 };
  ^
[ 67%] Building CXX object lib/fs/CMakeFiles/fs.dir/inputstream.cc.o
In file included from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/filesystem.h:21:0,
                 from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/inputstream.cc:19:
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/namenode_protocol.h:40:2: warning: extra ‘;’ [-Wpedantic]
 };
  ^
Linking CXX static library libfs.a
[ 67%] Built target fs
Scanning dependencies of target reader
[ 69%] Building CXX object lib/reader/CMakeFiles/reader.dir/remote_block_reader.cc.o
Linking CXX static library libreader.a
[ 69%] Built target reader
Scanning dependencies of target rpc
[ 72%] Building CXX object lib/rpc/CMakeFiles/rpc.dir/rpc_connection.cc.o
[ 74%] Building CXX object lib/rpc/CMakeFiles/rpc.dir/rpc_engine.cc.o
Linking CXX static library librpc.a
[ 74%] Built target rpc
Scanning dependencies of target hdfsppjni
[ 76%] Building CXX object bindings/java/CMakeFiles/hdfsppjni.dir/block_reader.cc.o
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/bindings/java/block_reader.cc:20:57: fatal error: me_haohui_libhdfspp_NativeRemoteBlockReader.h: No such file or directory
 #include "me_haohui_libhdfspp_NativeRemoteBlockReader.h"
                                                         ^
compilation terminated.
make[2]: **\* [bindings/java/CMakeFiles/hdfsppjni.dir/block_reader.cc.o] Error 1
make[1]: **\* [bindings/java/CMakeFiles/hdfsppjni.dir/all] Error 2
make: **\* [all] Error 2

I've searched full source code, but no file named me_haohui_libhdfspp_NativeRemoteBlockReader.h, is it right ?

**Comment by bobhansen** [comment]
I'm not precisely sure.

It's trying to build the java JNI bindings (that are used in the unit tests).  Are you building the whole hadoop tree, or just the libhdfspp part?  Perhaps you need to build the rest of the client tree first.

-B

On 02/19/2016 01:31 AM, Mrknowledge wrote:

I've got errors while make libhdfspp source code :

[root@Sla3 build]# make
[ 2%] Running C++ protocol buffer compiler on ClientNamenodeProtocol.proto
[ 4%] Running C++ protocol buffer compiler on datatransfer.proto
[ 6%] Running C++ protocol buffer compiler on hdfs.proto
[ 9%] Running C++ protocol buffer compiler on Security.proto
[ 11%] Running C++ protocol buffer compiler on IpcConnectionContext.proto
[ 13%] Running C++ protocol buffer compiler on ProtobufRpcEngine.proto
[ 16%] Running C++ protocol buffer compiler on RpcHeader.proto
[ 18%] Running C++ protocol buffer compiler on acl.proto
[ 20%] Running C++ protocol buffer compiler on xattr.proto
[ 23%] Running C++ protocol buffer compiler on encryption.proto
[ 25%] Running C++ protocol buffer compiler on inotify.proto
Scanning dependencies of target proto
[ 27%] Building CXX object lib/proto/CMakeFiles/proto.dir/datatransfer.pb.cc.o
[ 30%] Building CXX object lib/proto/CMakeFiles/proto.dir/hdfs.pb.cc.o
[ 32%] Building CXX object lib/proto/CMakeFiles/proto.dir/Security.pb.cc.o
[ 34%] Building CXX object lib/proto/CMakeFiles/proto.dir/IpcConnectionContext.pb.cc.o
[ 37%] Building CXX object lib/proto/CMakeFiles/proto.dir/ProtobufRpcEngine.pb.cc.o
[ 39%] Building CXX object lib/proto/CMakeFiles/proto.dir/RpcHeader.pb.cc.o
[ 41%] Building CXX object lib/proto/CMakeFiles/proto.dir/acl.pb.cc.o
[ 44%] Building CXX object lib/proto/CMakeFiles/proto.dir/xattr.pb.cc.o
[ 46%] Building CXX object lib/proto/CMakeFiles/proto.dir/encryption.pb.cc.o
[ 48%] Building CXX object lib/proto/CMakeFiles/proto.dir/inotify.pb.cc.o
[ 51%] Building CXX object lib/proto/CMakeFiles/proto.dir/ClientNamenodeProtocol.pb.cc.o
Linking CXX static library libproto.a
[ 51%] Built target proto
Scanning dependencies of target common
[ 53%] Building CXX object lib/common/CMakeFiles/common.dir/hdfs.cc.o
[ 55%] Building CXX object lib/common/CMakeFiles/common.dir/base64.cc.o
[ 58%] Building CXX object lib/common/CMakeFiles/common.dir/datatransfer_sasl.cc.o
[ 60%] Building CXX object lib/common/CMakeFiles/common.dir/sasl_digest_md5.cc.o
[ 62%] Building CXX object lib/common/CMakeFiles/common.dir/status.cc.o
Linking CXX static library libcommon.a
[ 62%] Built target common
Scanning dependencies of target fs
[ 65%] Building CXX object lib/fs/CMakeFiles/fs.dir/filesystem.cc.o
In file included from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/filesystem.h:21:0,
from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/filesystem.cc:19:
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/namenode_protocol.h:40:2: warning: extra �;� [-Wpedantic]
};
^
[ 67%] Building CXX object lib/fs/CMakeFiles/fs.dir/inputstream.cc.o
In file included from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/filesystem.h:21:0,
from /home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/inputstream.cc:19:
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/lib/fs/namenode_protocol.h:40:2: warning: extra �;� [-Wpedantic]
};
^
Linking CXX static library libfs.a
[ 67%] Built target fs
Scanning dependencies of target reader
[ 69%] Building CXX object lib/reader/CMakeFiles/reader.dir/remote_block_reader.cc.o
Linking CXX static library libreader.a
[ 69%] Built target reader
Scanning dependencies of target rpc
[ 72%] Building CXX object lib/rpc/CMakeFiles/rpc.dir/rpc_connection.cc.o
[ 74%] Building CXX object lib/rpc/CMakeFiles/rpc.dir/rpc_engine.cc.o
Linking CXX static library librpc.a
[ 74%] Built target rpc
Scanning dependencies of target hdfsppjni
[ 76%] Building CXX object bindings/java/CMakeFiles/hdfsppjni.dir/block_reader.cc.o
/home/hkx/hadoop/git_project/libhdfs++/libhdfspp/src/main/native/bindings/java/block_reader.cc:20:57: fatal error: me_haohui_libhdfspp_NativeRemoteBlockReader.h: No such file or directory
#include "me_haohui_libhdfspp_NativeRemoteBlockReader.h"
^
compilation terminated.
make[2]: **\* [bindings/java/CMakeFiles/hdfsppjni.dir/block_reader.cc.o] Error 1
make[1]: **\* [bindings/java/CMakeFiles/hdfsppjni.dir/all] Error 2
make: **\* [all] Error 2

I've searched full source code, but no file named me_haohui_libhdfspp_NativeRemoteBlockReader.h, is it right ?

�

**Comment by jamesclampffer** [comment]
That's a header generated by javah for the JNI bindings.  It's been a while since I worked on this tree so I don't remember if you have to explicitly run javah.  Development for this project has moved to https://issues.apache.org/jira/browse/HDFS-8707.  If you checkout the HDFS-8707 branch of hadoop and do a build with maven everything should work.  That branch is significantly more stable and has some extra functionality.

**Comment by Mrknowledge** [comment]
Right. I build all HDFS-8707 branch, it's OK. Cheers.
