### ISSUE TITLE
libhdfspp: undefined reference to `hdfsCreateDirectory'

### ISSUE THREAD

**Issue by Mrknowledge** [haohui/libhdfspp#50]
I've include "hdfspp/hdfs_ext.h" in my .h file, and linked libhdfspp.a, but still some hdfs functions not found.

g++ CProcessMgr.o main.o CTcpServer.o CContextLogToTxt.o CTcpService.o CTimerService.o CChildProcess.o Signal.o StringFun.o CFileName.o dlmonitor.o log.o common.o database.o dldatabase.o dlconfig.o mail.o -o ../file_combine -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -L/usr/java/jdk1.7.0_21/jre/lib/amd64/server ../myzlib/libmyzlib.a /home/hadoop_8707/hadoop-HDFS-8707-8d215aa/hadoop-hdfs-project/hadoop-hdfs-native-client/target/main/native/libhdfspp/libhdfspp.a ../../mainarch/lib/libmysqlclient.a ../../mainarch/os/libconfigdbproc.a /home/hkx/hadoop/protobuf-2.5.0/src/.libs/libprotobuf.a -lpthread -lssl -lcrypto -lxml2 -ljvm
CChildProcess.o: In function `hdfsConn(char const*, unsigned short)':
/home/filecombine/os/../source/CChildProcess.cpp:43: undefined reference to`hdfsBuilderSetForceNewInstance'
CChildProcess.o: In function `CChildProcess::CombineFile(CFileName&, std::vector<CChildProcess::SORTINFO, std::allocator<CChildProcess::SORTINFO> >&, std::map<std::string, hdfsFile_internal*, std::less<std::string>, std::allocator<std::pair<std::string const, hdfsFile_internal*> > >&, hdfs_internal*)':
/home/filecombine/os/../source/CChildProcess.cpp:226: undefined reference to`hdfsCreateDirectory'
/home/filecombine/os/../source/CChildProcess.cpp:278: undefined reference to `hdfsExists'
/home/filecombine/os/../source/CChildProcess.cpp:378: undefined reference to`hdfsRename'
/home/filecombine/os/../source/CChildProcess.cpp:390: undefined reference to `hdfsWrite'
/home/filecombine/os/../source/CChildProcess.cpp:411: undefined reference to`hdfsHFlush'
CChildProcess.o: In function `CChildProcess::UpdateFile(CFileName&, hdfs_internal*)':
/home/filecombine/os/../source/CChildProcess.cpp:528: undefined reference to`hdfsCopy'
/home/filecombine/os/../source/CChildProcess.cpp:545: undefined reference to `hdfsDelete'
/home/filecombine/os/../source/CChildProcess.cpp:546: undefined reference to`hdfsRename'
/home/filecombine/os/../source/CChildProcess.cpp:555: undefined reference to `hdfsMove'
CChildProcess.o: In function`CChildProcess::SortFile(CChildProcess::SORTINFO const&, hdfs_internal_)':
/home/filecombine/os/../source/CChildProcess.cpp:595: undefined reference to `hdfsCopy'
/home/filecombine/os/../source/CChildProcess.cpp:656: undefined reference to`hdfsDelete'
/home/filecombine/os/../source/CChildProcess.cpp:657: undefined reference to `hdfsRename'
/home/filecombine/os/../source/CChildProcess.cpp:666: undefined reference to`hdfsMove'
collect2: error: ld returned 1 exit status
make: *_\* [EXE] Error 1

**Comment by bobhansen** [comment]
Currently, only the builder, open, seek, and read methods are supported on the HDFS-8707 branch (see bindings/c for the complete list).  It is under active development, and the other NameNode operations should be fairly simple to implement, but they're not there yet.

We debated creating a header file that consisted of only the implemented methods, but decided it would be best to continue using the existing hdfs.h file to guarantee compatibility.

Sorry for the inconvenience.
-B

On 02/22/2016 10:49 PM, Mrknowledge wrote:

I've include "hdfspp/hdfs_ext.h" in my .h file, and linked libhdfspp.a, but still some hdfs functions not found.

g++ CProcessMgr.o main.o CTcpServer.o CContextLogToTxt.o CTcpService.o CTimerService.o CChildProcess.o Signal.o StringFun.o CFileName.o dlmonitor.o log.o common.o database.o dldatabase.o dlconfig.o mail.o ParameraterBuilder.o StoreBuffer.o -o ../file_combine_nosort-1.5.2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -L/usr/java/jdk1.7.0_21/jre/lib/amd64/server ../myzlib/libmyzlib.a /home/hkx/hadoop/git_project/hadoop_8707/hadoop-HDFS-8707-8d215aa/hadoop-hdfs-project/hadoop-hdfs-native-client/target/main/native/libhdfspp/libhdfspp.a ../../mainarch/lib/libmysqlclient.a ../../mainarch/os/libconfigdbproc.a /home/hkx/hadoop/protobuf-2.5.0/src/.libs/libprotobuf.a -lpthread -lssl -lcrypto -lxml2 -ljvm
CChildProcess.o: In function hdfsConn(char const_, unsigned short)':
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:43: undefined reference tohdfsBuilderSetForceNewInstance'
CChildProcess.o: In function CChildProcess::CombineFile(CFileName&, std::vector<CChildProcess::SORTINFO, std::allocator<CChildProcess::SORTINFO> >&, std::map<std::string, hdfsFile_internal_, std::lessstd::string, std::allocator<std::pair<std::string const, hdfsFile_internal*> > >&, hdfs_internal_)':
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:226: undefined reference tohdfsCreateDirectory'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:278: undefined reference to hdfsExists'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:378: undefined reference tohdfsRename'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:390: undefined reference to hdfsWrite'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:411: undefined reference tohdfsHFlush'
CChildProcess.o: In function CChildProcess::UpdateFile(CFileName&, hdfs_internal_)':
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:528: undefined reference tohdfsCopy'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:545: undefined reference to hdfsDelete'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:546: undefined reference tohdfsRename'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:555: undefined reference to hdfsMove'
CChildProcess.o: In functionCChildProcess::SortFile(CChildProcess::SORTINFO const&, hdfs_internal)':
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:595: undefined reference to hdfsCopy'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:656: undefined reference tohdfsDelete'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:657: undefined reference to hdfsRename'
/home/hkx/hadoop/filecombine/FileCombine-1.5.2/os/../source/CChildProcess.cpp:666: undefined reference tohdfsMove'
collect2: error: ld returned 1 exit status
make: *\* [EXE] Error 1

�

**Comment by Mrknowledge** [comment]
Hi, bob. Would you like to implement all funcitons in hdfs.h ?

**Comment by bobhansen** [comment]
Absolutely.  HDFS-8707 is in-progress, and we've had contributions from several companies.  Our goal is to get the read path (unauthenticated and authenticated) and all NameNode paths complete before submitting for inclusion into the hadoop main project.  We can then do the write paths and other outstanding features (encrypted content, erase codes, etc.) in later releases.

-Bob

On 02/23/2016 03:43 PM, Mrknowledge wrote:

Hi, bob. Would you like to implement all funcitons in hdfs.h ?

�

**Comment by Mrknowledge** [comment]
Bob, this is great stuff. Thanks for doing this!
